theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"
auto-format = false
rulers = [120]
end-of-line-diagnostics = "hint"
default-yank-register = "+"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"
max-diagnostics = 5

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.statusline]
separator = "|"
left = ["mode","spacer","version-control","file-name","file-modification-indicator"]
right = ["spinner","workspace-diagnostics","spacer","position-percentage"]

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[keys.normal]
C-s = ":w"
"tab" = ":bn"
"S-tab" = ":bp"

# [keys.normal.f]
# m = ":fmt"

[keys.normal."space"]
x = ":bc"
